-- SUPERSEDED — use supabase/fix_admin.sql instead.
--
-- This promoted "the earliest customer", which turned out to be a test fixture:
-- verify-slots.ts and verify-supabase-tokens.ts create customer rows named
-- 'concurrency-probe' and 'verification-probe', and they predate any real
-- booking. Ordering by created_at was the wrong discriminator.
--
-- fix_admin.sql matches on the shape of a real LINE user id instead
-- ('U' followed by 32 hex characters), which no probe can satisfy.
